[package]
name = "opi_gpio_rs"
version = "1.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
inotify = "0.11.0"
log = "0.4.27"
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
